---
title: "project-code"
format: html
---

```{r}
# load data
library(tidyverse)
library(tidytuesdayR)

tuesdata <- tidytuesdayR::tt_load(2021, week = 29)

scoobydoo <- tuesdata$scoobydoo
```


```{r}
# individual monsters for TV series episodes

scoobydoo_monsters <- scoobydoo |>
  filter(season %in% c("1", "2","3", "4"),
         format == "TV Series") |>
  filter(monster_name != "NULL") |>
  mutate(unmasked = case_when(
    unmask_fred == TRUE | unmask_daphnie == TRUE | unmask_velma == TRUE | 
    unmask_shaggy == TRUE | unmask_scooby == TRUE | unmask_other == TRUE ~ "Yes", 
    TRUE ~ "No")) |>
  mutate(monster_amount = ifelse(title == "The Ghastly Ghost Town", 5, monster_amount),
         monster_amount = ifelse(title == "Me and My Shadow Demon", 3, monster_amount)) |>
  mutate(monster_name = str_replace(monster_name, "Dr. Phineus Phibes,Agent 1,Agent 2,Agent 3,Agent 4,Agent 5,Agent 6,Agent 7,Agent,8,Agent,9,Agent 10,Agent 11,Agent 12,Agent 13,Dr. Trebal", "Dr. Phineus Phibes,Agent 1,Agent 2,Agent 3,Agent 4,Agent 5,Agent 6,Agent 7,Agent 8,Agent 9,Agent 10,Agent 11,Agent 12,Agent 13,Dr. Trebal"),
         monster_name = str_replace(monster_name, "Dr. Phineus Phibes,Agent 3,Agent 4,Agent 5,Agent 6,Agent 7,Agent,9,Agent 10,Agent 11,Agent 12,Agent 13,Dr. Trebal,Misty Swiss", "Dr. Phineus Phibes,Agent 3,Agent 4,Agent 5,Agent 6,Agent 7,Agent 9,Agent 10,Agent 11,Agent 12,Agent 13,Dr. Trebal,Misty Swiss"),
         monster_name = str_replace(monster_name, "Dr. Phineus Phibes,Dr. Trebla,Agent 1,Agent 2,Mark,Ricky,Agent,4,Agent 7,Agent 11", "Dr. Phineus Phibes,Dr. Trebla,Agent 1,Agent 2,Mark,Ricky,Agent 4,Agent 7,Agent 11")) |>
  select(title, season, series_name, contains("monster"), unmasked) |>
  pivot_longer(cols = c(monster_name, monster_gender, monster_type, monster_subtype, monster_species), names_to = "monster_var", values_to = "monster") |>
  separate(monster, c("1monster", "2monster", "3monster", "4monster", "5monster", "6monster", "7monster", "8monster", "9monster", "10monster", "11monster", "12monster", "13monster", "14monster", "15monster"), sep = ",") |>
  pivot_longer(cols = ends_with("monster"), names_to = "monster_num", values_to = "monster_value") |>
  pivot_wider(names_from = monster_var, values_from = monster_value) |>
  separate(monster_num, c("monster_num", "x"), sep = "m") |>
  mutate(monster_num = as.numeric(monster_num)) |>
  select(-x) |>
  na.omit() |>
  mutate(monster_type = ifelse(monster_type == "Disugised", "Disguised", monster_type),
          monster_type = ifelse(monster_type == "Disguise", "Disguised", monster_type)) |>
  mutate(monster_type = str_trim(monster_type, side = "left"))
```

```{r}
# how many times to characters appear?
scoobydoo |>
  select(batman, scrappy_doo, scooby_dum, hex_girls, blue_falcon) |>
  pivot_longer(cols = everything(), names_to = "character", values_to = "yn") |>
  group_by(character, yn) |>
  summarize(n = n()) |>
  pivot_wider(names_from = yn, values_from = n) 
```

```{r}
# make "guest" dataset
scoobydoo_guest <- scoobydoo |>
  select(batman, blue_falcon, hex_girls, scooby_dum, scrappy_doo, series_name, title, imdb, engagement) |>
  pivot_longer(cols = c(batman, blue_falcon, hex_girls, scooby_dum, scrappy_doo), names_to = "character", values_to = "TF")
```

```{r}
# boxplots of imdb ratings for guest characters
scoobydoo_guest |>
  filter(imdb != "NULL") |>
  ggplot(aes(x=TF, y=as.numeric(imdb)))+
  geom_boxplot()+
  facet_wrap(~character)
```
```{r}
# calculating mean and sd for imdb, engagement
scoobydoo |>
  select(imdb, engagement) |>
  filter(imdb != "NULL",
         engagement != "NULL") |>
  mutate(imdb = as.numeric(imdb),
         engagement = as.numeric(engagement)) |>
  summarize(mean_imdb = mean(imdb),
            sd_imdb = sd(imdb),
            mean_engage = mean(engagement),
            sd_engage = sd(engagement)) 
```
 
```{r}
# distribution of imdb, engagement
scoobydoo |>
  filter(engagement != "NULL") |>
  ggplot(aes(x=as.numeric(engagement)))+
  geom_histogram()+
  labs(title = "distribution of engagement (normal scale)",
       x= "engagement")

scoobydoo |>
  filter(engagement != "NULL") |>
  ggplot(aes(x=as.numeric(engagement)))+
  geom_histogram()+
  scale_x_log10()+
  labs(title = "distribution of engagement (log scale)",
       x = "log(engagement)")


scoobydoo |>
  filter(imdb != "NULL") |>
  ggplot(aes(x=as.numeric(imdb)))+
  geom_boxplot()

```

```{r}
# missing entries
scoobydoo |>
  select(imdb) |>
  filter(imdb == "NULL") |>
  count(imdb) 

scoobydoo |>
  select(engagement) |>
  filter(engagement == "NULL") |>
  count(engagement)
```

```{r}
# MODEL 1: Popular Guest effect (Batman OR Hex Girls OR Scrappy-Doo)
model1 <- lm(as.numeric(imdb) ~ as.numeric(batman == "TRUE" | hex_girls == "TRUE" | scrappy_doo == "TRUE"), 
             data = scoobydoo %>% filter(imdb != "NULL"))
summary(model1)

# MODEL 2: Individual character effects
model2 <- lm(as.numeric(imdb) ~ as.numeric(batman == "TRUE") + 
                                    as.numeric(hex_girls == "TRUE") + 
                                    as.numeric(scrappy_doo == "TRUE"),
             data = scoobydoo %>% filter(imdb != "NULL"))
summary(model2)

# MODEL 3: All guest characters (comprehensive)
model3 <- lm(as.numeric(imdb) ~ as.numeric(batman == "TRUE") + 
                                    as.numeric(hex_girls == "TRUE") + 
                                    as.numeric(scrappy_doo == "TRUE") +
                                    as.numeric(blue_falcon == "TRUE") +
                                    as.numeric(scooby_dum == "TRUE"),
             data = scoobydoo %>% filter(imdb != "NULL"))
summary(model3)

# Get tidy coefficient outputs
library(broom)
cat("=== MODEL 1: Popular Guest Effect ===\n")
print(tidy(model1))

cat("\n=== MODEL 2: Specific Characters (Research Question) ===\n")
print(tidy(model2))

cat("\n=== MODEL 3: All Guest Characters ===\n")
print(tidy(model3))
```

